# Generated by Django 2.1.7 on 2019-03-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='description',
            new_name='living_space',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_bestseller',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_deal_of_the_day',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_new_arrival',
        ),
        migrations.AddField(
            model_name='room',
            name='House_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='apartment_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='entrance_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='flat_area',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='home_adress',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='kitchen_area',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='total_floors',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
