# Generated by Django 2.1.7 on 2019-03-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0002_auto_20190321_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Обьект')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата Обновления')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='цена')),
                ('home_adress', models.CharField(max_length=100, unique=True, verbose_name='Полный адрес')),
                ('House_number', models.IntegerField(verbose_name='Номер дома')),
                ('entrance_number', models.IntegerField(verbose_name='Номер подьезда')),
                ('apartment_number', models.IntegerField(verbose_name='Номер квартиры')),
                ('total_floors', models.IntegerField(verbose_name='Этажей в доме')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('flat_area', models.IntegerField(verbose_name='Общая площадь')),
                ('kitchen_area', models.IntegerField(verbose_name='Площадь кухни')),
                ('living_space', models.TextField(verbose_name='Описание квартиры')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='product/')),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='author',
        ),
        migrations.RemoveField(
            model_name='room',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='room',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='room',
            name='House_number',
            field=models.IntegerField(verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='room',
            name='apartment_number',
            field=models.IntegerField(verbose_name='Номер квартиры'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='room',
            name='entrance_number',
            field=models.IntegerField(verbose_name='Номер подьезда'),
        ),
        migrations.AlterField(
            model_name='room',
            name='flat_area',
            field=models.IntegerField(verbose_name='Общая площадь'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='room',
            name='home_adress',
            field=models.CharField(max_length=100, unique=True, verbose_name='Полный адрес'),
        ),
        migrations.AlterField(
            model_name='room',
            name='kitchen_area',
            field=models.IntegerField(verbose_name='Площадь кухни'),
        ),
        migrations.AlterField(
            model_name='room',
            name='living_space',
            field=models.TextField(verbose_name='Описание квартиры'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Обьект'),
        ),
        migrations.AlterField(
            model_name='room',
            name='old_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='room',
            name='total_floors',
            field=models.IntegerField(verbose_name='Этажей в доме'),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата Обновления'),
        ),
    ]
