# Generated by Django 2.1.7 on 2019-03-24 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0003_auto_20190324_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leninskiy', models.CharField(max_length=50, unique=True, verbose_name='Ленинский')),
                ('Dzerzhinsky', models.CharField(max_length=50, unique=True, verbose_name='Дзержинский')),
                ('Tagilstroevsky', models.CharField(max_length=50, unique=True, verbose_name='Тагилстроевский')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminsite.District'),
            preserve_default=False,
        ),
    ]
