# Generated by Django 2.1.7 on 2019-03-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0004_auto_20190324_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='Dzerzhinsky',
        ),
        migrations.RemoveField(
            model_name='district',
            name='Tagilstroevsky',
        ),
        migrations.RemoveField(
            model_name='district',
            name='leninskiy',
        ),
        migrations.AddField(
            model_name='district',
            name='District',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Район'),
            preserve_default=False,
        ),
    ]
