# Generated by Django 2.1.7 on 2019-03-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0005_auto_20190324_0706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='District',
            new_name='district',
        ),
    ]
