# Generated by Django 2.1.7 on 2019-03-24 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0007_auto_20190324_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=50, unique=True, verbose_name='Катигории квартир')),
            ],
            options={
                'verbose_name': 'Катигории квартир',
                'verbose_name_plural': 'Катигории квартир',
            },
        ),
        migrations.AlterField(
            model_name='room',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.Сategories'),
        ),
    ]
