# Generated by Django 2.1.7 on 2019-03-24 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0008_auto_20190324_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='сategories',
            old_name='district',
            new_name='сategories',
        ),
        migrations.RemoveField(
            model_name='room',
            name='home_adress',
        ),
        migrations.AddField(
            model_name='room',
            name='сategories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminsite.Сategories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.District'),
        ),
    ]
